<a href="https://colab.research.google.com/github/afzalasar7/Data-Science/blob/main/Week%209%20Numpy%20and%20Visualization/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

```python
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
```

Output:
```
Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>
```

Yes, there is a difference in the data type of variables `list_` and `array_list`. `list_` is a standard Python list, while `array_list` is a NumPy array.

# Q2. Code to print the data type of each and every element of both the variables list_ and array_list.

```python
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))
```

Output:
```
Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
```

In the list `list_`, all elements are of type `str`, whereas in the NumPy array `array_list`, the elements are of type `numpy.str_`.

# Q3. Code to print the data types of each and every element present in both the variables, list_ and array_list after converting array_list to dtype int.

```python
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))
```

Output:
```
Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
```

After converting `array_list` to dtype `int`, the elements in the NumPy array are now of type `numpy.int64`.

# Q4. Code to find the characteristics of variable num_array: shape and size.

```python
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)
```

Output:
```
Shape of num_array: (2, 3)
Size of num_array: 6
```

The variable `num_array` has a shape of (2, 3), which means it is a 2x3 matrix, and it has a size of 6, which represents the total number of elements in the array.

# Q5. Code to create a numpy array of a 3x3 matrix containing zeros only using a numpy array creation function.

```python
import numpy as np

zeros_array = np.zeros((3, 3))

print(zeros_array)
```

Output:
```
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```

The `zeros_array` is a 3x3 matrix containing zeros only.

# Q6. Code to create an identity matrix of shape (5, 5) using numpy functions.

```python
import numpy as np

identity_matrix = np.eye(5)

print(identity_matrix)
```

Output:
```
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
```

The `identity_matrix` is a 5x5 matrix with ones along the main diagonal and zeros elsewhere, making it an identity matrix.